[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput"]

[phases.setup]
nixPkgs = ["python311"]

[start]
cmd = "gunicorn carbonwise.wsgi --bind 0.0.0.0:$PORT"